var tipuedrop = {"pages": [
     {"title": "Sch. 40 Tee", "thumb": "img/irrigation3.png", "text": "Sch. 40 Tee", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Sch. 40 PVC", "thumb": "img/irrigation2.png", "text": "Sch. 40 PVC", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Sch. 40 Elbow", "thumb": "img/irrigation3.png", "text": "Sch. 40 Elbow", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Class 200 PVC", "thumb": "img/pvc_class_200.png", "text": "Class 200 PVC", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Sch. 40 Male Adapter", "thumb": "img/uvr_pvc_male_adapter.png", "text": "Sch. 40 Male Adapter", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Sch. 40 Coupling", "thumb": "img/sch_coupling.png", "text": "Sch. 40 Coupling", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "UVR Elbow", "thumb": "img/irrigation2.png", "text": "UVR Elbow", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Sch. 40 Elbow Slip x Thread", "thumb": "img/irrigation2.png", "text": "ch. 40 Elbow Slip x Thread", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Class 200 Coupling", "thumb": "img/sch_coupling.png", "text": "Class 200 Coupling", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Class 200 Tee Slip x Thread", "thumb": "img/irrigation3.png", "text": "Class 200 Tee Slip x Thread", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Crepe Myrtle", "thumb": "img/tree_1.png", "text": "Crepe Myrtle", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Lombardy Poplar", "thumb": "img/tree_2.png", "text": "Lombardy Poplar", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Southern Live Oak", "thumb": "img/tree_3.png", "text": "Southern Live Oak", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "California Pepper", "thumb": "img/tree_5.png", "text": "California Pepper", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "London Plane", "thumb": "img/tree_6.png", "text": "London Plane", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Boxwood", "thumb": "img/shrubs_1.png", "text": "Boxwood", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Boxwood", "thumb": "img/shrubs_2.png", "text": "Boxwood", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Rosemary", "thumb": "img/ground_cover_2.png", "text": "Rosemary", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Decomposed Granite", "thumb": "img/aggregates_1.png", "text": "Decomposed Granite", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Forest Floor Mulch", "thumb": "img/aggregates_2.png", "text": "Forest Floor Mulch", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Mixed Pebbles", "thumb": "img/aggregates_3.png", "text": "Mixed Pebbles", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Mexican Beach Pebbles", "thumb": "img/aggregates_4.png", "text": "Mexican Beach Pebbles", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Amendment", "thumb": "img/aggregates_5.png", "text": "Amendment", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Washed Plasted Sand", "thumb": "img/aggregates_6.png", "text": "Washed Plasted Sand", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Decorative Boulders", "thumb": "img/aggregates_7.png", "text": "Decorative Boulders", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Arizona Flagstone", "thumb": "img/aggregates_8.png", "text": "Arizona Flagstone", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Brute Bucket", "thumb": "img/job_materials_1.png", "text": "Brute Bucket", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Burlap Tarp", "thumb": "img/job_materials_2.png", "text": "Burlap Tarp", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Grading Rake", "thumb": "img/job_materials_3.png", "text": "Grading Rake", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Lodge Pole", "thumb": "img/job_materials_4.png", "text": "Lodge Pole", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Fertilizer Tablets", "thumb": "img/job_materials_5.png", "text": "Fertilizer Tablets", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Root Barrier", "thumb": "img/job_materials_6.png", "text": "Root Barrier", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Guy Wires", "thumb": "img/job_materials_7.png", "text": "Guy Wires", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
     {"title": "Jute Netting", "thumb": "img/job_materials_8.png", "text": "Jute Netting", "tags": "JavaScript js", "loc": "http://www.tipue.com/search"},
]};
